### ISSUE TITLE
Allow skipping particular lines

### ISSUE THREAD

**Issue by feinbd** [PrincetonUniversity/blocklint#18]
I have a line that reads a table from a database which has the word "master" in it.   I obviously can't change this.  I need a way to flag this line as not to be checked by blocklint, not the whole file.  I don't see a way to do this.

**Comment by troycomi** [comment]
If you can add an inline comment, any line ending in `blocklint: pragma` will be ignored.  This was added with PR #6 and an example is [here](https://github.com/PrincetonUniversity/blocklint/pull/6/files#diff-fb85f1a6a278e7935ccd6d1b2fb74a422e3451526f77b3ac6d20c826df78692a).  I apologize that the feature didn't get put into the readme!

I'll leave this open to remind me to add a section to the readme.  I hope the pragma resolves your issue, otherwise let me know more details.

**Comment by feinbd** [comment]
This works, thank you!
